name: Feature request
description: Request an enhancement
type: Feature
body:
  - type: checkboxes
    attributes:
      label: AI Policy
      description: Review our [AI Policy](https://tree-sitter.github.io/tree-sitter/6-contributing.html#ai-policy).
      options:
        - label: I have read the AI Policy and this issue complies with it.
          required: true

  - type: markdown
    attributes:
      value: |
        Before requesting: search [existing feature requests](https://github.com/tree-sitter/tree-sitter/labels/enhancement).

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved."
      placeholder: "No smurf icons available. Smurfs are useful because ..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem? Is it worth the cost?"
    validations:
      required: false
