/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define TREE_SITTER_STABILITY "___dtrace_stability$tree_sitter$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define TREE_SITTER_TYPEDEFS "___dtrace_typedefs$tree_sitter$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	TREE_SITTER_QUERY_CURSOR_ADVANCE_STATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__advance__state$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_ADVANCE_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__advance__state$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_BRANCH_STATE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__branch__state$v1$75696e7431365f74$75696e7431365f74$75696e7431365f74$696e74$75696e7433325f74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_BRANCH_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__branch__state$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_CAPTURE(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__capture$v1$63686172202a$75696e7431365f74$75696e7431365f74$75696e7433325f74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_CAPTURE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__capture$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_DEFER_FINISHING_PATTERN(arg0) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__defer__finishing__pattern$v1$75696e7433325f74(arg0); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DEFER_FINISHING_PATTERN_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__defer__finishing__pattern$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_DISCARD_STATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__discard__state$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DISCARD_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__discard__state$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_DROP_STATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__drop__state$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DROP_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__drop__state$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_ENTER_NODE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__enter__node$v1$63686172202a$63686172202a$75696e7433325f74$75696e7433325f74$75696e7433325f74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_ENTER_NODE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__enter__node$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_FAILED_MATCH(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__failed__match$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_FAILED_MATCH_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__failed__match$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_FINISH_PATTERN(arg0) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__finish__pattern$v1$75696e7433325f74(arg0); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_FINISH_PATTERN_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__finish__pattern$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_HALT() \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__halt$v1(); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_HALT_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__halt$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_LEAVE_NODE(arg0) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__leave__node$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_LEAVE_NODE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__leave__node$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_MISSING_PARENT_NODE() \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__missing__parent__node$v1(); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_MISSING_PARENT_NODE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__missing__parent__node$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_CURSOR_SPLIT_STATE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__cursor__split__state$v1$75696e7433325f74$75696e7433325f74$756e7369676e656420696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_CURSOR_SPLIT_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__cursor__split__state$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_STATE_ABANDON(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__state__abandon$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_STATE_ABANDON_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__state__abandon$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_STATE_NO_CAPTURE_LISTS() \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__state__no__capture__lists$v1(); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_STATE_NO_CAPTURE_LISTS_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__state__no__capture__lists$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREE_SITTER_QUERY_STATE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREE_SITTER_TYPEDEFS); \
	__dtrace_probe$tree_sitter$query__state__start$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREE_SITTER_STABILITY); \
} while (0)
#define	TREE_SITTER_QUERY_STATE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$tree_sitter$query__state__start$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$tree_sitter$query__cursor__advance__state$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__advance__state$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__branch__state$v1$75696e7431365f74$75696e7431365f74$75696e7431365f74$696e74$75696e7433325f74(uint16_t, uint16_t, uint16_t, int, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__branch__state$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__capture$v1$63686172202a$75696e7431365f74$75696e7431365f74$75696e7433325f74(const char *, uint16_t, uint16_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__capture$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__defer__finishing__pattern$v1$75696e7433325f74(uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__defer__finishing__pattern$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__discard__state$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__discard__state$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__drop__state$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__drop__state$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__enter__node$v1$63686172202a$63686172202a$75696e7433325f74$75696e7433325f74$75696e7433325f74(const char *, const char *, uint32_t, uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__enter__node$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__failed__match$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__failed__match$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__finish__pattern$v1$75696e7433325f74(uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__cursor__finish__pattern$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__halt$v1(void);
extern int __dtrace_isenabled$tree_sitter$query__cursor__halt$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__leave__node$v1$63686172202a(const char *);
extern int __dtrace_isenabled$tree_sitter$query__cursor__leave__node$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__missing__parent__node$v1(void);
extern int __dtrace_isenabled$tree_sitter$query__cursor__missing__parent__node$v1(void);
extern void __dtrace_probe$tree_sitter$query__cursor__split__state$v1$75696e7433325f74$75696e7433325f74$756e7369676e656420696e74(uint32_t, uint32_t, unsigned int);
extern int __dtrace_isenabled$tree_sitter$query__cursor__split__state$v1(void);
extern void __dtrace_probe$tree_sitter$query__state__abandon$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$tree_sitter$query__state__abandon$v1(void);
extern void __dtrace_probe$tree_sitter$query__state__no__capture__lists$v1(void);
extern int __dtrace_isenabled$tree_sitter$query__state__no__capture__lists$v1(void);
extern void __dtrace_probe$tree_sitter$query__state__start$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$tree_sitter$query__state__start$v1(void);

#else

#define	TREE_SITTER_QUERY_CURSOR_ADVANCE_STATE(arg0, arg1) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_ADVANCE_STATE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_BRANCH_STATE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_BRANCH_STATE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_CAPTURE(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_CAPTURE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_DEFER_FINISHING_PATTERN(arg0) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DEFER_FINISHING_PATTERN_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_DISCARD_STATE(arg0, arg1) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DISCARD_STATE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_DROP_STATE(arg0, arg1) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_DROP_STATE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_ENTER_NODE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_ENTER_NODE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_FAILED_MATCH(arg0, arg1) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_FAILED_MATCH_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_FINISH_PATTERN(arg0) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_FINISH_PATTERN_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_HALT() \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_HALT_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_LEAVE_NODE(arg0) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_LEAVE_NODE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_MISSING_PARENT_NODE() \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_MISSING_PARENT_NODE_ENABLED() (0)
#define	TREE_SITTER_QUERY_CURSOR_SPLIT_STATE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_CURSOR_SPLIT_STATE_ENABLED() (0)
#define	TREE_SITTER_QUERY_STATE_ABANDON(arg0, arg1, arg2) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_STATE_ABANDON_ENABLED() (0)
#define	TREE_SITTER_QUERY_STATE_NO_CAPTURE_LISTS() \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_STATE_NO_CAPTURE_LISTS_ENABLED() (0)
#define	TREE_SITTER_QUERY_STATE_START(arg0, arg1) \
do { \
	} while (0)
#define	TREE_SITTER_QUERY_STATE_START_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
