/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define TREESITTER_STABILITY "___dtrace_stability$treesitter$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define TREESITTER_TYPEDEFS "___dtrace_typedefs$treesitter$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	TREESITTER_PARSER_LEX() \
do { \
	__asm__ volatile(".reference " TREESITTER_TYPEDEFS); \
	__dtrace_probe$treesitter$parser__lex$v1(); \
	__asm__ volatile(".reference " TREESITTER_STABILITY); \
} while (0)
#define	TREESITTER_PARSER_LEX_ENABLED() \
	({ int _r = __dtrace_isenabled$treesitter$parser__lex$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREESITTER_PARSER_REDUCE() \
do { \
	__asm__ volatile(".reference " TREESITTER_TYPEDEFS); \
	__dtrace_probe$treesitter$parser__reduce$v1(); \
	__asm__ volatile(".reference " TREESITTER_STABILITY); \
} while (0)
#define	TREESITTER_PARSER_REDUCE_ENABLED() \
	({ int _r = __dtrace_isenabled$treesitter$parser__reduce$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREESITTER_STATE_ABANDON(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " TREESITTER_TYPEDEFS); \
	__dtrace_probe$treesitter$state__abandon$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " TREESITTER_STABILITY); \
} while (0)
#define	TREESITTER_STATE_ABANDON_ENABLED() \
	({ int _r = __dtrace_isenabled$treesitter$state__abandon$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREESITTER_STATE_RAN_OUT_OF_CAPTURE_LISTS() \
do { \
	__asm__ volatile(".reference " TREESITTER_TYPEDEFS); \
	__dtrace_probe$treesitter$state__ran_out_of_capture_lists$v1(); \
	__asm__ volatile(".reference " TREESITTER_STABILITY); \
} while (0)
#define	TREESITTER_STATE_RAN_OUT_OF_CAPTURE_LISTS_ENABLED() \
	({ int _r = __dtrace_isenabled$treesitter$state__ran_out_of_capture_lists$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	TREESITTER_STATE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " TREESITTER_TYPEDEFS); \
	__dtrace_probe$treesitter$state__start$v1$75696e7433325f74$75696e7433325f74(arg0, arg1); \
	__asm__ volatile(".reference " TREESITTER_STABILITY); \
} while (0)
#define	TREESITTER_STATE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$treesitter$state__start$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$treesitter$parser__lex$v1(void);
extern int __dtrace_isenabled$treesitter$parser__lex$v1(void);
extern void __dtrace_probe$treesitter$parser__reduce$v1(void);
extern int __dtrace_isenabled$treesitter$parser__reduce$v1(void);
extern void __dtrace_probe$treesitter$state__abandon$v1$756e7369676e656420696e74$756e7369676e656420696e74$756e7369676e656420696e74(unsigned int, unsigned int, unsigned int);
extern int __dtrace_isenabled$treesitter$state__abandon$v1(void);
extern void __dtrace_probe$treesitter$state__ran_out_of_capture_lists$v1(void);
extern int __dtrace_isenabled$treesitter$state__ran_out_of_capture_lists$v1(void);
extern void __dtrace_probe$treesitter$state__start$v1$75696e7433325f74$75696e7433325f74(uint32_t, uint32_t);
extern int __dtrace_isenabled$treesitter$state__start$v1(void);

#else

#define	TREESITTER_PARSER_LEX() \
do { \
	} while (0)
#define	TREESITTER_PARSER_LEX_ENABLED() (0)
#define	TREESITTER_PARSER_REDUCE() \
do { \
	} while (0)
#define	TREESITTER_PARSER_REDUCE_ENABLED() (0)
#define	TREESITTER_STATE_ABANDON(arg0, arg1, arg2) \
do { \
	} while (0)
#define	TREESITTER_STATE_ABANDON_ENABLED() (0)
#define	TREESITTER_STATE_RAN_OUT_OF_CAPTURE_LISTS() \
do { \
	} while (0)
#define	TREESITTER_STATE_RAN_OUT_OF_CAPTURE_LISTS_ENABLED() (0)
#define	TREESITTER_STATE_START(arg0, arg1) \
do { \
	} while (0)
#define	TREESITTER_STATE_START_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
