#!/usr/bin/env bash

# If `CC` isn't set, pick a default compiler
if hash clang 2>/dev/null; then
  : ${CC:=clang}
else
  : ${CC:=gcc}
fi

CC="$CC" meson build/c \
  --buildtype=release  \
  -Dc_args="$CFLAGS"

ninja -C build/c
