#!/bin/bash

set -e

EMSCRIPTEN_VERSION=$(cat "$(dirname "$0")/../cli/loader/emscripten-version")

mkdir -p target
EMSDK_DIR="./target/emsdk"

(
  if [ ! -f "$EMSDK_DIR/emsdk" ]; then
    echo 'Downloading emscripten SDK...'
    git clone https://github.com/emscripten-core/emsdk.git $EMSDK_DIR
  fi

  cd $EMSDK_DIR

  echo 'Updating emscripten SDK...'
  git reset --hard
  git pull
  ./emsdk list

  echo 'Installing emscripten...'
  ./emsdk install $EMSCRIPTEN_VERSION

  echo 'Activating emscripten...'
  ./emsdk activate $EMSCRIPTEN_VERSION
) >&2

(
  echo "source \"$EMSDK_DIR/emsdk_env.sh\""
)
