#!/usr/bin/env bash

set -e

symbol_file=$(mktemp)

while read -r wasm_file; do
  wasm-objdump                   \
    --details "$wasm_file"    \
    --section Import             \
    | grep -Eo '<\w+>'           \
    | tr -d '<>'                 \
    >> "$symbol_file"
done < <(find target -maxdepth 2 -name 'tree-sitter-*.wasm')

sort -u -o "$symbol_file" "$symbol_file"
cat "$symbol_file"
