#!/usr/bin/env bash

set -e

cd lib/binding_web

if [ ! -d "node_modules/chai" ] || [ ! -d "node_modules/mocha" ]; then
  echo "Installing test dependencies..."
  npm install
fi

./node_modules/.bin/mocha
