#!/usr/bin/env bash

set -e

cd lib/binding_web

if [[ ! -d node_modules/chai ]] || [[ ! -d node_modules/mocha ]]; then
  printf 'Installing test dependencies...\n'
  npm install
fi

node_modules/.bin/mocha
