name: Matrix definition

on: public # stub - it never happens

jobs:
  matrix:
    steps: [run: echo] # stub - suppress errors
    runs-on: ubuntu    #
    strategy:
      matrix:
        platform:
        - linux-arm64       #
        - linux-arm         #
        - linux-armhf       #
        - linux-armv5te     #
        - linux-armv7l      #
        - linux-x64         #
        - linux-x86         #
        - linux-i586        #
        - linux-mips        #
        - linux-mips64      #
        - linux-mipsel      #
        - linux-mips64el    #
        - linux-powerpc     #
        - linux-powerpc64   #
        - linux-powerpc64el #
        - linux-riscv64gc   # #2712
        - linux-s390x       #
        - linux-sparc64     #
        - linux-thumbv7neon #
        - windows-arm64     #
        - windows-x64       # <-- No C library build - requires an additional adapted Makefile for `cl.exe` compiler
        - windows-x86       #     -- // --
        - macos-arm64       # <-- MacOS M1/M2 - no tests, only CLI build to be published on release artifacts
        - macos-x64         #

        include:
        # When adding a new `target`:
        # 1. Define a new platform alias above
        # 2. Add a new record to a matrix map in `cli/npm/install.js`
        - { platform: linux-arm64       , target: aarch64-unknown-linux-gnu           , os: ubuntu-latest            }
        - { platform: linux-arm         , target: arm-unknown-linux-gnueabi           , os: ubuntu-latest            }
        - { platform: linux-armhf       , target: arm-unknown-linux-gnueabihf         , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-armv5te     , target: armv5te-unknown-linux-gnueabi       , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-armv7l      , target: armv7-unknown-linux-gnueabihf       , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-x64         , target: x86_64-unknown-linux-gnu            , os: ubuntu-20.04             } #2272
        - { platform: linux-x86         , target: i686-unknown-linux-gnu              , os: ubuntu-latest            }
        - { platform: linux-i586        , target: i586-unknown-linux-gnu              , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-mips        , target: mips-unknown-linux-gnu              , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-mips64      , target: mips64-unknown-linux-gnuabi64       , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-mipsel      , target: mipsel-unknown-linux-gnu            , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-mips64el    , target: mips64el-unknown-linux-gnuabi64     , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-powerpc     , target: powerpc-unknown-linux-gnu           , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-powerpc64   , target: powerpc64-unknown-linux-gnu         , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-powerpc64el , target: powerpc64le-unknown-linux-gnu       , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-riscv64gc   , target: riscv64gc-unknown-linux-gnu         , os: ubuntu-latest  , tier: 3 } #2712
        - { platform: linux-s390x       , target: s390x-unknown-linux-gnu             , os: ubuntu-latest            }
        - { platform: linux-sparc64     , target: sparc64-unknown-linux-gnu           , os: ubuntu-latest  , tier: 2 }
        - { platform: linux-thumbv7neon , target: thumbv7neon-unknown-linux-gnueabihf , os: ubuntu-latest  , tier: 2 }
        - { platform: windows-arm64     , target: aarch64-pc-windows-msvc             , os: windows-latest           }
        - { platform: windows-x64       , target: x86_64-pc-windows-msvc              , os: windows-latest           }
        - { platform: windows-x86       , target: i686-pc-windows-msvc                , os: windows-latest           }
        - { platform: macos-arm64       , target: aarch64-apple-darwin                , os: macos-latest             }
        - { platform: macos-x64         , target: x86_64-apple-darwin                 , os: macos-latest             }

        # Cross compilers for C library
        - { platform: linux-arm64       , cc: aarch64-linux-gnu-gcc           , ar: aarch64-linux-gnu-ar           , use-cross: true }
        - { platform: linux-arm         , cc: arm-linux-gnueabi-gcc           , ar: arm-linux-gnueabi-ar           , use-cross: true }
        - { platform: linux-armhf       , cc: arm-unknown-linux-gnueabihf-gcc , ar: arm-unknown-linux-gnueabihf-ar , use-cross: true }
        - { platform: linux-armv5te     , cc: arm-linux-gnueabi-gcc           , ar: arm-linux-gnueabi-ar           , use-cross: true }
        - { platform: linux-armv7l      , cc: arm-linux-gnueabihf-gcc         , ar: arm-linux-gnueabihf-ar         , use-cross: true }
        - { platform: linux-x86         , cc: i686-linux-gnu-gcc              , ar: i686-linux-gnu-ar              , use-cross: true }
        - { platform: linux-i586        , cc: i686-linux-gnu-gcc              , ar: i686-linux-gnu-ar              , use-cross: true }
        - { platform: linux-mips        , cc: mips-linux-gnu-gcc              , ar: mips-linux-gnu-ar              , use-cross: true }
        - { platform: linux-mips64      , cc: mips64-linux-gnuabi64-gcc       , ar: mips64-linux-gnuabi64-ar       , use-cross: true }
        - { platform: linux-mipsel      , cc: mipsel-linux-gnu-gcc            , ar: mipsel-linux-gnu-ar            , use-cross: true }
        - { platform: linux-mips64el    , cc: mips64el-linux-gnuabi64-gcc     , ar: mips64el-linux-gnuabi64-ar     , use-cross: true }
        - { platform: linux-powerpc     , cc: powerpc-linux-gnu-gcc           , ar: powerpc-linux-gnu-ar           , use-cross: true }
        - { platform: linux-powerpc64   , cc: powerpc64-linux-gnu-gcc         , ar: powerpc64-linux-gnu-ar         , use-cross: true }
        - { platform: linux-powerpc64el , cc: powerpc64le-linux-gnu-gcc       , ar: powerpc64le-linux-gnu-ar       , use-cross: true }
        - { platform: linux-riscv64gc   , cc: riscv64-linux-gnu-gcc           , ar: riscv64-linux-gnu-ar           , use-cross: true } #2712
        - { platform: linux-s390x       , cc: s390x-linux-gnu-gcc             , ar: s390x-linux-gnu-ar             , use-cross: true }
        - { platform: linux-sparc64     , cc: sparc64-linux-gnu-gcc           , ar: sparc64-linux-gnu-ar           , use-cross: true }
        - { platform: linux-thumbv7neon , cc: arm-linux-gnueabihf-gcc         , ar: arm-linux-gnueabihf-ar         , use-cross: true }

        # Rust toolchains
        - { platform: linux-mips     , rust-toolchain: 1.71.1 }
        - { platform: linux-mips64   , rust-toolchain: 1.71.1 }
        - { platform: linux-mipsel   , rust-toolchain: 1.71.1 }
        - { platform: linux-mips64el , rust-toolchain: 1.71.1 }

        # See #2041 tree-sitter issue
        - { platform: windows-x64   , rust-test-threads: 1 }
        - { platform: windows-x86   , rust-test-threads: 1 }

        # CLI only build
        - { platform: windows-arm64 , cli-only: true }
        - { platform: macos-arm64   , cli-only: true }
