name: CI

on:
  push:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up stable Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Lint Rust files
        run: make lint

      - name: Install Taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo@0.10.0

      - name: Lint TOML files
        run: make lint-toml

      - name: Lint web files
        run: make lint-web

      # rustdoc's JSON output is nightly-only and unstable
      - name: Set up pinned nightly Rust toolchain
        run: rustup toolchain install nightly-2026-09-03 --profile minimal

      - name: Check regex error kinds
        run: cargo xtask check-regex-error-kinds

      - name: Check Wasm stdlib
        uses: actions/github-script@v9
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/scripts/wasm_stdlib.js`;
            const script = require(scriptPath);
            return script({ github, context, core });

  sanitize:
    uses: ./.github/workflows/sanitize.yml

  build:
    uses: ./.github/workflows/build.yml
