name: Update Emscripten

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read

jobs:
  update-emscripten:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up stable Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run emscripten update xtask
        env:
          GIT_AUTHOR_NAME: dependabot[bot]
          GIT_AUTHOR_EMAIL: 49699333+dependabot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: dependabot[bot]
          GIT_COMMITTER_EMAIL: 49699333+dependabot[bot]@users.noreply.github.com
        run: cargo xtask update-emscripten

      - name: Push updated version
        run: git push origin HEAD:$GITHUB_HEAD_REF
