name: Fast checks to fail fast on any simple code issues

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:

jobs:
  check_rust_formatting:
    name: Check Rust formating
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Run cargo fmt
      run: cargo fmt -- --check

  check_c_warnings:
    name: Check C warnings
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Make C library to check that it's able to compile without warnings
      run: make -j CFLAGS="-Werror"
